#!/bin/sh /etc/rc.common
#
# BeeeOn Project 2016
# Author: Matej Postolka <xposto02@stud.fit.vutbr.cz>
# Last modified: 2016-04-04
#

USE_PROCD=1
START=80
APP=adaapp
BINARY_PATH=/usr/bin
CONFIG_PATH=/etc/beeeon

registerIniFiles() {
	for f in $(ls $CONFIG_PATH/*.ini); do
		procd_set_param file "$f"
	done
}

start_service() {
	procd_open_instance
	procd_set_param command ${BINARY_PATH}/${APP}
	registerIniFiles()
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}
